name: Merge leetcode branch into main

on:
  push:
    branches:
      - leetcode

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge leetcode branch into master
        run: |
          git checkout master
          git merge leetcode
