name: Merge leetcode branch into main

on:
  push:
    branches:
      - leetcode

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge leetcode branch into master
      run: |
          git merge leetcode master
          git push master